# ASCP BOC {-}

ASCP BOC's Content Guideline for the Technologist in Blood Bank, BB(ASCP), and the Specialist in Blood Bank, SBB(ASCP), certification exams consists of five major content areas. The information below was last revised on ASCP's website Octoboer 2023

## **Blood Products** {-}

**Exam Percentage** BB(ASCP): 15% - 20% | SBB(ASCP): 10% - 15%

**Description** Donors, processing, storage, types of blood components, blood component quality contro

## **Blood Group Systems** {-}

**Exam Percentage** BB(ASCP): 15% - 20% | SBB(ASCP): 15% - 20%

**Description** Genetics, biochemistry/antigens, role of blood groups in transfusion

## **Immunology and Physiology** {-}

**Exam Percentage** BB(ASCP): 10% - 20% | SBB(ASCP): 15% - 20%

**Description** Immune response, immunoglobulins, antigen-antibody interactions, complement, physiology of blood, hemostasis and coagulation, HDFN, cytopenias, transplantation

## **Serologic and Molecular Testing** {-}

**Exam Percentage** BB(ASCP): 20% - 25% | SBB(ASCP): 20% - 25%

**Description** Routine tests, reagents, application of special tests and reagents, quality assurance

## **Transfusion Practice** {-}

**Exam Percentage** BB(ASCP): 15% - 20% | SBB(ASCP): 15% - 20%

**Description** Indications for transfusion, component therapy, adverse effects of transfusion, apheresis and extracorporeal circulation, blood administration and patient blood management
